### ISSUE TITLE
试了啊，看到了插件，但没有出现选择“查找下一个提供者”按钮

### ISSUE THREAD

**Issue by magicqn** [Dixeran/getLyrics#1]
1.下了mb_GetLyrics.dll mb_GetLyrics.dll.config mb_GetLyrics.pdb Newtonsoft.Json.dll这四个文件到plugin
2.插件里看到了getlyrics,钩了automaticlly选项
3.查不到歌词，也没有出现选择“查找下一个提供者”按钮，好像插件没有生效

musicbee版本是3.0.6335

**Comment by Dixeran** [comment]
可以尝试一下取消'自动选择歌词', 如果插件生效的话，会弹出一个列表供选择。

“查找下一个提供者”是在歌词面板右键菜单里面。
![qq 20170830100326](https://user-images.githubusercontent.com/22679810/29852096-ad304b6e-8d6a-11e7-8597-734fef197c27.png)
（歌词来源是'MUSICBEE PLUGIN'）
