### ISSUE TITLE
The GetLyrics did not work in my musicbee V3.1

### ISSUE THREAD

**Issue by AmalwayshereU** [Dixeran/getLyrics#2]
Dear sir or madam,
Hello, i am so sorry to tell you that your add-ons doesnot work in my musicbee, i am pretty sure that i have already choose "automatically choose". Although i do not know whether your add-one possessing any problem, i think i should give you amessage.
Thank you for devotion to musicbee. thank you very much.

**Comment by Dixeran** [comment]
Thanks for your feedback.
As I updated to the  latest version(3.1.6512), I found that I need to disable, save setting,  and re-enable the plugin once to make this plugin work.
Also, don't forget to right-click at "Lyrics" panel and "Redo Search" or "Search next provider".
